### ISSUE TITLE
No RealSense devices were found!

### ISSUE THREAD

**Issue by q8wwe** [gbr1/erwhi-hedgehog-ros#2]
when i run sensor launch file i got warning :
 [ WARN] [1583254734.919258582, 1810.150000000]: No RealSense devices were found!

**Comment by gbr1** [comment]
You have to launch **bringup.launch** with all robot parts mounted and connected.

**Comment by q8wwe** [comment]
I'm actually confused, how is the realsense simulated while the camera plugin is kinect
(libgazebo_ros_openni_kinect.so).
And why realsense plugin isn't use (librealsense_gazebo_plugin.so).

**Comment by gbr1** [comment]
@q8wwe when this software was created realsense ros package was really poor, e.g. no gazebo simulation or no cad model was shared.

You can easily create a depth camera in gazebo using the openni_kinect and setting right parameters, so I created a custom camera that have same D435 parameters.

**Comment by gbr1** [comment]
@q8wwe can you explain your issue in a better way?
At the moment the topic is "No RealSense devices were found!", so it is not a problem of Erwhi ros, but about Realsense.

**Comment by q8wwe** [comment]
it is working great with real sense and to tell you the truth realsense D435 dragged my attention. How you use it in the simulation and how you run launch file : roslaunch realseense2_camera rs_camera.launch ,
Without getting the warning mentioned in the topic .
Can you elaborate on how you did it ? I want to understand how the linking done between that launch file and the D435 . I think you used that to get point cloud , is that correct ?

**Comment by gbr1** [comment]
In gazebo.launch gazebo flag is true when launching file bringup.launch:
https://github.com/gbr1/erwhi-hedgehog-ros/blob/kinetic/erwhi_gazebo/launch/erwhi_gazebo.launch#L56

Now have a look at bringup.launch, there is a conditional case that doesn't launch sensor.launch:
https://github.com/gbr1/erwhi-hedgehog-ros/blob/kinetic/erwhi_bringup/launch/bringup.launch#L28

I close this issue because it is offtopic and probably solved your issue.
